config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :episodes
  resources :shows
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
end

app/models/show.rb
class Show < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]

  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to episodes_url, notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def episode_params
      params.require(:episode).permit(:title, :season, :episode, :airdate, :runtime)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :update, :destroy]

  # GET /shows
  # GET /shows.json
  def index
    @shows = Show.all
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: 'Show was successfully created.' }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to shows_url, notice: 'Show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def show_params
      params.require(:show).permit(:title, :summary, :artwork, :genre, :url, :watched)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/episodes/_form.html.erb
<%= form_with(model: episode, local: true) do |form| %>
  <% if episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
        <% episode.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :season %>
    <%= form.number_field :season %>
  </div>

  <div class="field">
    <%= form.label :episode %>
    <%= form.number_field :episode %>
  </div>

  <div class="field">
    <%= form.label :airdate %>
    <%= form.datetime_select :airdate %>
  </div>

  <div class="field">
    <%= form.label :runtime %>
    <%= form.datetime_select :runtime %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Episodes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Season</th>
      <th>Episode</th>
      <th>Airdate</th>
      <th>Runtime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= episode.title %></td>
        <td><%= episode.season %></td>
        <td><%= episode.episode %></td>
        <td><%= episode.airdate %></td>
        <td><%= episode.runtime %></td>
        <td><%= link_to 'Show', episode %></td>
        <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
        <td><%= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/new.html.erb
<h1>New Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @episode.title %>
</p>

<p>
  <strong>Season:</strong>
  <%= @episode.season %>
</p>

<p>
  <strong>Episode:</strong>
  <%= @episode.episode %>
</p>

<p>
  <strong>Airdate:</strong>
  <%= @episode.airdate %>
</p>

<p>
  <strong>Runtime:</strong>
  <%= @episode.runtime %>
</p>

<%= link_to 'Edit', edit_episode_path(@episode) %> |
<%= link_to 'Back', episodes_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WatchPartyPlanner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shows/_form.html.erb
<%= form_with(model: show, local: true) do |form| %>
  <% if show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
        <% show.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_area :summary %>
  </div>

  <div class="field">
    <%= form.label :artwork %>
    <%= form.text_field :artwork %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :watched %>
    <%= form.check_box :watched %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shows/edit.html.erb
<h1>Editing Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shows</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Summary</th>
      <th>Artwork</th>
      <th>Genre</th>
      <th>Url</th>
      <th>Watched</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shows.each do |show| %>
      <tr>
        <td><%= show.title %></td>
        <td><%= show.summary %></td>
        <td><%= show.artwork %></td>
        <td><%= show.genre %></td>
        <td><%= show.url %></td>
        <td><%= show.watched %></td>
        <td><%= link_to 'Show', show %></td>
        <td><%= link_to 'Edit', edit_show_path(show) %></td>
        <td><%= link_to 'Destroy', show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Show', new_show_path %>

app/views/shows/new.html.erb
<h1>New Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Back', shows_path %>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @show.title %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @show.summary %>
</p>

<p>
  <strong>Artwork:</strong>
  <%= @show.artwork %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @show.genre %>
</p>

<p>
  <strong>Url:</strong>
  <%= @show.url %>
</p>

<p>
  <strong>Watched:</strong>
  <%= @show.watched %>
</p>

<%= link_to 'Edit', edit_show_path(@show) %> |
<%= link_to 'Back', shows_path %>